### ISSUE TITLE
add : KPT

### ISSUE THREAD

**Issue by devbong92** [team06-morning2kim/morning2kim-intro#21]
[ KPT ]
> https://brunch.co.kr/@jinha0802/35

[ Keep ]
` 현재 만족하고 있는 부분 `
` 계속 이어갔으면 하는 부분 `

[ Problem ] 
` 불편하게 느끼는 부분 `
` 개선이 필요하다고 생각되는 부분 ` 

[ Try ]
` Problem에 대한 해결책 `
` 다음 회고 때 판별 가능한 것 `
` 당장 실행가능한 것 `

**Comment by devbong92** [comment]
[ Keep ]
- 웃으면서 진행하는 좋은 분위기

[ Problem ] 
- 적극적인 태도

[ Try ]
- 기능 찾아보기

**Comment by DevJames91** [comment]
[Keep]

- 협업을 위한 충분한 의사소통

[Problem]
- 누가 해주겠지 라는 게으름 버리기

[Try]
- 좀더 많은 자료를 탐구하여 정보 공유

**Comment by Tcoat1** [comment]
[ Keep ]
충분한 의사소통과 즐겁게 한 것
[ Problem ]
조금은 더 적극적이고 열심히 하는 것

[ Try ]
팀 프로젝트 시간 외에도 개인적으로 공부하는 시간을 늘리기

**Comment by rettytnova** [comment]
keep
상대방에게 짜증이나 화를 내지 않고 서로 존중하는 모습으로 의사소통하기
problem
코딩에 집중하기
try
팀프로젝트를 포함한 기본기에 도움되는 기반이 되는 지식들을 함께 공부하기
