### ISSUE TITLE
feat: 팀원 소개 / 취미 추천 내용 작성

### ISSUE THREAD

**Issue by devbong92** [team06-morning2kim/morning2kim-intro#9]
## 아래 내용을 복사하여 댓글로 작성해주세요.

[ 팀원 소개 ] 
- 이름
- 사진 [ 본인사진 ] 
- 취미
- MBTI
- 스타일(성격)

[ 취미 소개 ] 
- 취미명
- 취미 이미지 
- 취미 설명

**Comment by DevJames91** [comment]
김현하
사진: 링크
MBTI: INTP
스타일: 음식에 진심

취미명: 누워있기
취미 이미지: 링크
취미 설명: 1분이라도 더 누워있어야 근성장에 도움이 되기에..

**Comment by devbong92** [comment]
[ 팀원 소개 ]
- 이름 : 전봉준
- 사진 [ 본인사진 ] : 추가예정
- 취미 : 여행 
- MBTI : INTP
- 스타일(성격) : 조용함 

[ 취미 소개 ]
- 취미명 : 여행 
- 취미 이미지 : 추가예정
- 취미 설명 : 즉흥여행 ( 터미널이나 기차역에서 바로 갈 수 있는 곳으로 이동하여 즐김 )

**Comment by Tcoat1** [comment]
[ 팀원 소개 ]

이름 김진엽
사진 [ 본인사진 ]
취미 음악듣기,게임
MBTI ENFP
스타일(성격) 어느무리 에서든 광대포지션을 유지함
[ 취미 소개 ]

취미명 음악듣기,사운드 엔지니어
취미 이미지 
취미 설명 아티스트들의 앨범 발매용, 유튜브 업로드용 음악들을 MIX&Mastering 하는 것을 즐겨하며 보컬로 참여 하는것도 좋아함

**Comment by rettytnova** [comment]
[ 팀원 소개 ]

이름 : 오은택
사진 : 추후 게시
취미 : 게임
MBTI : INT4 (잘 모름)
스타일(성격) : 뭐든 문제가 생기면 해결해야 직성이 풀림
[ 취미 소개 ]

취미명 컴퓨터 게임
취미 이미지 
취미 설명 : 님도 해보셈 재밌음
